import { Signal, Workspace } from "@/types";

export const MOCK_WORKSPACE: Workspace = {
  id: "workspace-1",
  user_email: "founder@example.com",
  product_description: "Project management software for construction companies with robust API and field reporting.",
  icp_description: "Construction project managers at companies with 50-500 employees.",
  competitors: ["Procore", "Buildertrend", "Fieldwire"],
  keywords: ["construction management software", "field reporting app"],
  email_digest_enabled: true,
  email_digest_time: "09:00",
  created_at: new Date().toISOString(),
};

export const MOCK_SIGNALS: Signal[] = [
  {
    id: "sig-1",
    workspace_id: "workspace-1",
    source_url: "https://reddit.com/r/construction/comments/123",
    source_type: "reddit",
    title: "We're switching from HubSpot, what are people actually using?",
    intent_score: 9,
    intent_level: "Hot",
    signal_type: "evaluation",
    summary: "User with 200-person sales team actively evaluating CRM alternatives after price increase. Mentions they need better reporting and API access.",
    recommended_action: "Reply to this thread directly — they are evaluating right now and have budget",
    status: "new",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    demo: true
  },
  {
    id: "sig-2",
    workspace_id: "workspace-1",
    source_url: "https://g2.com/reviews/456",
    source_type: "g2",
    title: "Honest review: Procore has gotten worse since their acquisition",
    intent_score: 8,
    intent_level: "Hot",
    signal_type: "complaint",
    summary: "Verified reviewer from 150-person company expressing strong frustration with competitor's declining support and missing features. Mentions actively looking for alternatives.",
    recommended_action: "Reach out to this reviewer directly via LinkedIn — they are primed to switch",
    person_name: "Alex Johnson",
    company_name: "Apex Builders",
    status: "new",
    scraped_at: new Date(Date.now() - 3600000).toISOString(),
    created_at: new Date(Date.now() - 3600000).toISOString(),
    demo: true
  },
  {
    id: "sig-3",
    workspace_id: "workspace-1",
    source_url: "https://news.ycombinator.com/item?id=789",
    source_type: "hackernews",
    title: "Ask HN: What tools are you using for sales prospecting in 2026?",
    intent_score: 6,
    intent_level: "Warm",
    signal_type: "question",
    summary: "Active HN thread with 47 comments discussing sales tooling. Multiple users mention pain points with existing solutions.",
    recommended_action: "Add a thoughtful comment to this thread positioning your solution",
    status: "saved",
    scraped_at: new Date(Date.now() - 7200000).toISOString(),
    created_at: new Date(Date.now() - 7200000).toISOString(),
    demo: true
  },
  {
    id: "sig-4",
    workspace_id: "workspace-1",
    source_url: "https://linkedin.com/posts/101",
    source_type: "linkedin",
    title: "We just replaced our entire sales stack — here's what we learned",
    intent_score: 5,
    intent_level: "Warm",
    signal_type: "switching",
    summary: "VP of Sales at 300-person SaaS company documenting their vendor switch process. Post has 200+ engagements and active discussion in comments.",
    recommended_action: "Engage with this post and connect with the author — they influence buying decisions",
    person_name: "Sarah Williams",
    status: "new",
    scraped_at: new Date(Date.now() - 86400000).toISOString(),
    created_at: new Date(Date.now() - 86400000).toISOString(),
    demo: true
  },
  {
    id: "sig-5",
    workspace_id: "workspace-1",
    source_url: "https://reddit.com/r/sales/comments/202",
    source_type: "reddit",
    title: "Best practices for outbound sales automation in 2026?",
    intent_score: 3,
    intent_level: "Cold",
    signal_type: "question",
    summary: "Early-stage founder asking for tool recommendations for their first sales hire. Small company but potential early adopter.",
    recommended_action: "Monitor this account — they may become a buyer as they grow",
    status: "new",
    scraped_at: new Date(Date.now() - 172800000).toISOString(),
    created_at: new Date(Date.now() - 172800000).toISOString(),
    demo: true
  }
];
